name: build-on-release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows64
          - StandaloneLinux64

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v4
        with:
          path: Hypermania/Library
          key: Hypermania-Library-${{ matrix.targetPlatform }}-${{ hashFiles('Hypermania/Packages/packages-lock.json', 'Hypermania/ProjectSettings/ProjectVersion.txt', 'Hypermania/ProjectSettings/ProjectSettings.asset') }}
          restore-keys: |
            Hypermania-Library-${{ matrix.targetPlatform }}-
            Hypermania-Library-

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: Hypermania

      - name: Zip build
        run: |
          cd build/${{ matrix.targetPlatform }}
          zip -r ../../Hypermania-${{ matrix.targetPlatform }}-${GITHUB_REF_NAME}.zip .

      - name: Upload asset to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: Hypermania-${{ matrix.targetPlatform }}-${{ github.ref_name }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
